name = "lx-music-server"
main = "src/index.ts"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "USER_SYNC"
class_name = "UserSyncDO"

[[kv_namespaces]]
binding = "KV"
id = "98171be805274d1e94362120cb2ebb7b"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["UserSyncDO"]

[vars]
LX_USERS = "LX_USERS_PLACEHOLDER"
SERVER_NAME = "LX Music Server"
